/*
 * PixelOrchestra — logoData.js
 * tenchi.jpg から自動生成（tools/img2voxel.py）。手で編集しない
 */
export const TENCHI = {
  palette: {"w": "#f2f6fa", "n": "#163450", "m": "#1a5378", "c": "#1c6a9e", "b": "#1f7fc0", "i": "#e6edf4"},
  rows: [
    '......................................................................................................',
    '............................w....wwwwww.................wwwwww..............wwwwww.w..................',
    '....wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww........',
    '...wwwwwwwwwwwwwwwwwwwwwwwwwnwwwwnnnnnnwwwwwwww.....wwwwnnnnnnwwwwwwwwwwwwwwnnnnnnwnwwwwwwwwwww.......',
    '..wwnnnnnnnnnnnnnnnnnnnnnnnwnnnnnnnnnnnnnnnnnnww..wwwwnnnnnnnnnnnnnnnnnnnnnnnnnnnnwnnnnnnnnnnnwwww....',
    '..wwniiiiiiiiiiiiiiiiiiiiinwnniinnniiiinniiinnwwwwwwnnnnniiiinnnnniiiniiinnnnnnnnnnnnnnniiiinnwwwww...',
    '..wwniiiiiiiiiiiiiiiiiiiiinwniiinnniiiinniiinnnwwwnnnnniiiiiiiinnniiiniiinnnniiinnnniiiniiiinnnnnnww..',
    '..wwniiiiiiiiiiiiiiiiiiiiinwniiinnniiiinniiinnnnnnnnniiiiiiiiiiinniiiniiinnnniiinnniiiiiiiiiiiiinnww..',
    '..wwniiiiiiiiiiiiiiiiiiiiinwniiinniiiiiiiiiiiiiiinnniiiiiinniiiinniiiniiinnnniiinnniiiiiiiiiiiiiinww..',
    '..wwniiiiiiiiiiiiiiiiiiiinnwniiinniiiiiiiiiiiiiiinnniiiiiiiiiiiinniiiniiinnnniiinnniiiiiiiiiiiiiinww..',
    '..wwnnnnnnnnniiiiinnnnnnnnnwniiinniiiiiiiiiiiiiiinnniiiiiiiiiiiinniiiniiinnnniiinniiiiiiiiiiiiiiinww..',
    '...wwwwwwwwnniiiiinnwwwwwwwwniiinniiiiiiiiiiiiiiinnniniiiiiiiiiinniiiniiinnnnnnnnnniiinniiiinnnnnnnww.',
    '...wwwwwwwwnniiiiinnwwwwwwwwniiinniiiiiiiiiiiiiiinnnnnnnnnnnnnnnnniiiniiinnnnnnnnnnninnniiiinnnnnnnww.',
    '..wwmmmmmmmmmiiiiimmmmmmmmmmmiiimmmiiiimmiiimmiiimmmmmmmmmmmmmmmmmiiimiiimmiiiiiimmiiiiiiiiiiiiiimmww.',
    '..wwmiiiiiiiiiiiiiiiiiiiiimiiiiiiimiiiimmiiimmiiimmimmiiiiiiiiiimmiiimiiimmmmmmmmmmiiiiiiiiiiiiiimmww.',
    '..wwmiiiiiiiiiiiiiiiiiiiiimiiiiiiimiiiimmiiimmiiimmmmmiiiiiiiiiimmiiimiiimmmmmmmmmmiiiiiiiiiiiiiimmww.',
    '.wwmmiiiiiiiiiiiiiiiiiiiiimiiiiiiimmiiimmiiimmiiimmmmmiiiimmmiiimmiiimiiimmiiiiiimmmiiiiiiiiiiiiimmww.',
    '.wwmmmiiiiiiiiiiiiiiiiiiiimmiiiiiimmiimmmiiimmmiimmmmmmiiimmmiiimmiimmiiimmiiiiiimmmmmmmmmmmmmmmmmmww.',
    '.wwmmmmmmmmmiiiiiiimmmmmmmmmiiiiimmmiimmmiiimmiiimmmmmmiiiiiiiiimmiimmiiimmiiiiimmmmmmmmmmmmmmmmmmmww.',
    '.wwmmmmmmmmmmiiiiimmmmmmmmmmmiiimmmmiimmmiiimmiiimmmmmmiimmmmiiimmiimmiiimmiiiiimmmmiiiiiiiiiiiimmmww.',
    '.wwmmmmmmmmmmiiiiimmmmmmmmmmmiiimmmmiimmmiiimmiiimmmmmmiiimmmiiimmiimmiiimmmmmiimmmmiiiiiiiiiiiiimmww.',
    '..wwwwwwwwccciiiiicciiiiiiiccciicccciiccciiicciiicccccciiiiiiiiccciiccciiccccciicccciiiiiiiiiiiicccww.',
    '...wwwwwwwccciiiiiccciiiiiiccciicccciiccciiicciiccciccciiiiiiiiccciiccciiccccciicccciiicccccciiicccww.',
    '.......wwccciiiiiiicciiiiiiccciicccciiccciiiccccccciccciiccccccccciiccciiccccciicccciiicccccciiicccww.',
    '....wwwwcccciiiiiiiccciiiiiccciicccciiccciiiccccccciccciiccccccccciiccciiccccciicccciiiiiiiiiiiicccww.',
    '...wwwwcccciiiiiiiiiccciiiiccciicccciiccciiiccccccccccciiicccccccciiccciiccccciicccciiiiiiiiiiiicccww.',
    '..wwcccccciiiiiiiiiiiccccccccciiiccciiccccccccciccccccciiiiiiiicccccccciiccccciicccccccccccccccccccww.',
    '.wwbbbbbbiiiiibbiiiiiibbbbbbbiiiibbbiibbbbbbbbbiibbbbbiiiibbbiibbbbbbbbiibbbbiiiibbbbbbbbbbbbbbbbbbww.',
    '.wwbbbbiiiiiibbbbiiiiiiibbbbiiiiibbbiiibbbbbbbiiibbbbiiiibbbbbibbbbbbbiiibbbbiiiiibbbbbbbbbbbbbbbbbww.',
    '.wwbbbiiiiiibbbbbbiiiiiiibbbiiibbbbbiiiiiiiiiiiiibbbbiiiibbbbbibbbiiiiiiibbbiiiiiiibbbbbbbbbbbbbbbbww.',
    '.wwbbbiiiiibbbbwbbbiiiiiibbbibbbbbbbiiiiiiiiiiiiibbbbiiiiibbbiibbbiiiiiiibbbiiiiiiiiiiiiiiiiiiiiibbww.',
    '.wwbbbiiiibbbbwwwbbbbiiiibbbbbbbbbbbiiiiiiiiiiiibbbbbiiiiiiiiiibbbiiiiiibbbbiiibbbiiiiiiiiiiiiiiibbww.',
    '.wwbbbibbbbbwww.wwbbbbbbibbbbbbwwwbbbbbbbbbbbbbbbbbbbibbbbbbbbbbbbiiibbbbbbbibbbbbbbbbbbbbbbbbbbbbbww.',
    '.wwbbbbbbbwwww...wwwbbbbbbbbwwwwwwbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbww.',
    '.wwbbbbbwwww......wwwwwbbbbwwww..wwbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbbbbbbbbbbbwwwbbbbbbbbbbbbbbbbbww.',
    '..wwwwwwww..........wwwwwwww......wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww..',
    '...wwwww...............wwww........wwwwwwwwwwwwww.wwwwwwwwwwwwwwwwwwwwwwwwwwwww...wwwwwwwwwwwwwwwww...',
    '......................................................................................................',
  ],
};
