/*
 * PixelOrchestra — logoData.js
 * tenchi.jpg から自動生成（tools/img2voxel.py）。手で編集しない
 */
export const TENCHI = {
  palette: {"w": "#f2f6fa", "n": "#163450", "b": "#1f7fc0", "d": "#12689d", "i": "#e6edf4"},
  rows: [
    '......................................................................................................',
    '............................w....wwwwww.................wwwwww..............wwwwww.w..................',
    '....wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww........',
    '...wwwwwwwwwwwwwwwwwwwwwwwwwnwwwwnnnnnnwwwwwwww.....wwwwnnnnnnwwwwwwwwwwwwwwnnnnnnwnwwwwwwwwwww.......',
    '..wwnnnnnnnnnnnnnnnnnnnnnnnwnnnnnnnnnnnnnnnnnnww..wwwwnnnnnnnnnnnnnnnnnnnnnnnnnnnnwnnnnnnnnnnnwwww....',
    '..wwniiiiiiiiiiiiiiiiiiiiinwnniinnniiiinniiinnwwwwwwnnnnniiiinnnnniiiniiinnnnnnnnnnnnnnniiiinnwwwww...',
    '..wwniiiiiiiiiiiiiiiiiiiiinwniiinnniiiinniiinnnwwwnnnnniiiiiiiinnniiiniiinnnniiinnnniiiniiiinnnnnnww..',
    '..wwniiiiiiiiiiiiiiiiiiiiinwniiinnniiiinniiinnnnnnnnniiiiiiiiiiinniiiniiinnnniiinnniiiiiiiiiiiiinnww..',
    '..wwniiiiiiiiiiiiiiiiiiiiinwniiinniiiiiiiiiiiiiiinnniiiiiinniiiinniiiniiinnnniiinnniiiiiiiiiiiiiinww..',
    '..wwniiiiiiiiiiiiiiiiiiiinnwniiinniiiiiiiiiiiiiiinnniiiiiiiiiiiinniiiniiinnnniiinnniiiiiiiiiiiiiinww..',
    '..wwnnnnnnnnniiiiinnnnnnnnnwniiinniiiiiiiiiiiiiiinnniiiiiiiiiiiinniiiniiinnnniiinniiiiiiiiiiiiiiinww..',
    '...wwwwwwwwnniiiiinnwwwwwwwwniiinniiiiiiiiiiiiiiinnniniiiiiiiiiinniiiniiinnnnnnnnnniiinniiiinnnnnnnww.',
    '...wwwwwwwwnniiiiinnwwwwwwwwniiinniiiiiiiiiiiiiiinnnnnnnnnnnnnnnnniiiniiinnnnnnnnnnninnniiiinnnnnnnww.',
    '..wwnnnnnnnnniiiiinnnnnnnnnnniiinnniiiinniiinniiinnnnnnnnnnnnnnnnniiiniiinniiiiiinniiiiiiiiiiiiiinnww.',
    '..wwniiiiiiiiiiiiiiiiiiiiiniiiiiiiniiiinniiinniiinninniiiiiiiiiinniiiniiinnnnnnnnnniiiiiiiiiiiiiinnww.',
    '..wwniiiiiiiiiiiiiiiiiiiiiniiiiiiiniiiinniiinniiinnbnniiiiiiiiiinniiiniiinnnnnnnnnniiiiiiiiiiiiiinnww.',
    '.wwbniiiiiiiiiiiiiiiiiiiiiniiiiiiinbiiinniiinniiinnbnniiiinnniiinniiiniiinniiiiiinnniiiiiiiiiiiiinnww.',
    '.wwbnbiiiiiiiiiiiiiiiiiiiinbiiiiiinbiibnniiinnbiinnbnnbiiibbbiiinniibniiinniiiiiinnnnnnnnnnnnnnnnnnww.',
    '.wwbnbbbbbbbiiiiiiibbbbbbbnbiiiiinnbiibnniiinniiinnbnnbiiiiiiiiinniibniiinniiiiibnnnnnnnnnnnnnnnnnnww.',
    '.wwbnnnnnnnnniiiiinnnnnnnnnnniiinnnbiibnniiinbiiinnbnnbiibnnniiinniibniiinniiiiibnnbiiiiiiiiiiiibnbww.',
    '.wwbnnnnnnnnniiiiinnnnnnnnnnniiinnnbiibnniiinbiiinnbnnbiiibbbiiinniibniiinnnnbiibnnbiiiiiiiiiiiiinbww.',
    '..wwwwwwwwbnbiiiiinniiiiiiibnbiinnnbiibnniiibniiinnbnnbiiiiiiiibnniibnbiinnnnbiibnnbiiiiiiiiiiiibnbww.',
    '...wwwwwwwbnbiiiiibnbiiiiiibbbiinbnbiibnniiinniibnbibbbiiiiiiiibnbiibnbiinbbnbiibbbbiiibbbbbniiibbbww.',
    '.......wwbbniiiiiiibbiiiiiibbbiibbbbiibbbiiibbbbbbbibbbiibbbbbbbbbiibbbiibbbbbiibbbbiiibbbbbbiiibbbww.',
    '....wwwwbbbbiiiiiiibbbiiiiibbbiibbbbiibbbiiibbbbbbbibbbiinbbbbbbbbiibbbiibbbbbiibbbbiiiiiiiiiiiibbbww.',
    '...wwwwbbbbiiiiiiiiibbbiiiibbbiibbbbiibbbiiibbbbbbbbbbbiiibbbbbbbbiibbbiibbbbbiibbbbiiiiiiiiiiiibbbww.',
    '..wwbbbbbbiiiiiiiiiiibbbbbbbbbiiibbbiibbbbbbbbbibbbbbbbiiiiiiiibbbbbbbbiibbbbbiibbbbbbbbbbbbbbbbbbbww.',
    '.wwbbbbbbiiiiibbiiiiiibbbbbbbiiiibbbiibbbbbbbbbiibbbbbiiiibbbiibbbbbbbbiibbbbiiiibbbbbbbbbbbbbbbbbbww.',
    '.wwbbbbiiiiiibbbbiiiiiiibbbbiiiiibbbiiibbbbbbbiiibbbbiiiibbbbbibbbbbbbiiibbbbiiiiibbbbbbbbbbbbbbbbbww.',
    '.wwbbbiiiiiibbbbbbiiiiiiibbbiiibbbbbiiiiiiiiiiiiibbbbiiiibbbbbibbbiiiiiiibbbiiiiiiibbbbbbbbbbbbbbbbww.',
    '.wwbbbiiiiibbbbwbbbiiiiiibbbibbbbbbbiiiiiiiiiiiiibbbbiiiiibbbiibbbiiiiiiibbbiiiiiiiiiiiiiiiiiiiiibbww.',
    '.wwbbbiiiibbbbwwwbbbbiiiibbbbbbbbbbbiiiiiiiiiiiibbbbbiiiiiiiiiibbbiiiiiibbbbiiibbbiiiiiiiiiiiiiiibbww.',
    '.wwbbbibbbbbwww.wwbbbbbbibbbbbbwwwbbbbbbbbbbbbbbbbbbbibbbbbbbbbbbbiiibbbbbbbibbbbbbbbbbbbbbbbbbbbbbww.',
    '.wwbbbbbbbwwww...wwwbbbbbbbbwwwwwwbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbww.',
    '.wwbbbbbwwww......wwwwwbbbbwwww..wwbbbbbbbbbbbbbbwbbbbbbbbbbbbbbbbbbbbbbbbbbbbbwwwbbbbbbbbbbbbbbbbbww.',
    '..wwwwwwww..........wwwwwwww......wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww..',
    '...wwwww...............wwww........wwwwwwwwwwwwww.wwwwwwwwwwwwwwwwwwwwwwwwwwwww...wwwwwwwwwwwwwwwww...',
    '......................................................................................................',
  ],
};
