/*
 * PixelOrchestra — randi3Data.js
 * 最終更新: 2026-09-21 / v0.3 / 生成元: PixelOrchestra（ユーザー提供の六面図シートから抽出）
 *
 * 出典：~/Desktop/Codex 画像 2026年9月21日 17_48_40.png（前・左・背・右・上・下の 6 面）
 * シートは陰影付きのレンダリング画なので、面積平均で 40 行のマス目に均してから 52 色へ減色した。
 * 4 面の高さが 342〜350px とばらついていた（1 枚ずつ独立に描かれた絵で、同一モデルの投影ではない）ため、
 * **各図を自分の高さで 40 行に正規化し、中央揃え**で重ねてある。
 *
 * 添字の約束（voxelPart のグリッドに合わせる）
 *   front[y][x] / back[y][x] … 背面図は左右反転して front と同じ向きに
 *   left [y][z] / right[y][z] … z=0 が背面。左側面図は画像左が正面なので反転済み
 *   top  [z][x] … 上面図を W×D に伸縮したマスク（'#' が有る所）。断面をここで切ると頭が丸くなる
 *   ※ 下面図はブーツと短パンだけで腕には効かないので取り込んでいない
 */
export const RANDI3 = {
  w: 19, h: 40, depth: 17,
  palette: {
    a: '#202834', b: '#233f5e', c: '#274f78', d: '#2f6593',
    e: '#42251e', f: '#45312c', g: '#4c4b58', h: '#4e7ea6',
    i: '#533d38', j: '#53657f', k: '#5591bd', l: '#5b2d24',
    m: '#63a4cf', n: '#6d2f2d', o: '#6d4d43', p: '#6f3528',
    q: '#713a28', r: '#714130', s: '#786264', t: '#804029',
    u: '#833935', v: '#865241', w: '#89412c', x: '#8b462e',
    y: '#8c4d2f', z: '#91b4c5', A: '#9c533b', B: '#9d7d69',
    C: '#9e9896', D: '#9f502d', E: '#a04b3a', F: '#a1424b',
    G: '#a2674c', H: '#a45939', I: '#a65f41', J: '#a95335',
    K: '#b75d35', L: '#ba5256', M: '#be5e43', N: '#bf6b4f',
    O: '#c27d62', P: '#c66736', Q: '#c85f4e', R: '#d16c38',
    S: '#d56b6d', T: '#db7967', U: '#de8481', V: '#dfa177',
    W: '#e29289', X: '#e3824b', Y: '#ecb38f', Z: '#f6cdb5',
  },
  front: [
    '...........AA......',
    '.....DKH...KI......',
    '.....rJRPyqKKx.....',
    '....ItqJRPtDJtvA...',
    '..DKRKxwJKDqtxKPy..',
    '.tKKPPPPJyDqtKPPw..',
    '..epqpDXXXPtxDwlf..',
    '.yKDDRXXXRJDPJtJKv.',
    'yKKJPXXPXDpxRKxDPKt',
    'yKqKXRDxPnnwKJEnxxq',
    'rqlKRDnFDLULELQFef.',
    '..qPKpFSQUWSSLFL...',
    '..lDtpxEXTTJJwnn...',
    '...qpAGisYYasMwHq..',
    '...GDKVcCZZcCOKTt..',
    '...GJNYCCZZCZOJGp..',
    '...lwATZZZZZVGt....',
    '....llqOZYZVxl.....',
    '...DDFLupwqnLFxy...',
    '..HVYsLUUUUUSsCVK..',
    '..AOVCsUWWWUssVXD..',
    '..UYOsksGOOshjNYV..',
    '.oVYNghkBBOBhgIYYI.',
    '.OVNtaghBjoyiapIVV.',
    'rvvvfuSWWYULEperGvi',
    'lFueeuLUzZWSSFeeuFu',
    '...sgdkhCcUSUSos...',
    'GOvGskmk.hUSSULvvTN',
    'NYQJBz.hhkCFTWUMPVO',
    '.NKtjjcdmkzjsUWFKN.',
    '...bdkkkhbhkhjBo...',
    '...chmmkdackmhcb...',
    '..chmmmkdadmmmmhc..',
    '..bdzzzmdahmzzmdb..',
    '...bcdddbabdddcb...',
    '....issgaaagssi....',
    '...pxvoie.erovtr...',
    '..tGONApe.etDNONv..',
    '..tOVOIle.eqHOVOy..',
    '..foooifa.afiooii..',
  ],
  back: [
    '..........Hy.......',
    '....vIMA..DJx......',
    '....rxPRPttKD......',
    '....yptKRJqJyp.....',
    '..yKPDqtKKwtqtJHA..',
    '.tKPKJDJRHPttKRPD..',
    '..lpptKXXXRxxDxqi..',
    '.qJDyKJtJKJKJwJKy..',
    'vJPDJPDwDKKRRxDKPD.',
    'vJwtwxJPRXPRKtpttt.',
    'rpfllqPRPRxDtnlef..',
    '..fnFuxDtDeeuQEl...',
    '...eFSFluSFFSSul...',
    '..lwxLSuFULFFntAq..',
    '..yKJpFLLnLLEwKOy..',
    '..pxDqIWSeSULtyAr..',
    '....tpvWSlSWGpr....',
    '....llsWSlSWFf.....',
    '...DIogUSaLUFiGHr..',
    '..DVYCjuSSSFgCYVJ..',
    '..ITVCkjSUSjhCVNA..',
    '..VZTsmkjjjkkjNYV..',
    '.GTVMidkkkkkdaIVVv.',
    'GOVNqfgjjjjjgapIVO.',
    'rAGveiLUWWWSFlervEl',
    'rvrfaiFLSUWUSuefrFr',
    '...BgdkkCuUWWSoB...',
    'IOItsmmmzdLUWWLtATM',
    'GVXKsk..hkhBWWULPXI',
    '.HJtbdcchkhjsUUFyI.',
    '...bdkkddbcdjssg...',
    '...chmmkdadkkhdc...',
    '..cdmzzmdadmmzmdc..',
    '..bchmmkdadkmmhcb..',
    '...abcccbabcdcba...',
    '....rGsga.aisvi....',
    '....wEvre.firEul...',
    '...yxDDtf.ftDDwqr..',
    '..lqyHAte.frAAxqi..',
    '...ffiifa.afoofef..',
  ],
  left: [
    '...........Dv....',
    '....yKHx.qJRv....',
    '....lxPPytPRq....',
    '...qttDPKwJxqIKv.',
    '..qDKKyJKDtqJPRD.',
    '.ltKRPDDPPtpDDwr.',
    '.xJRPDRXXXKqKJtyr',
    'tKPKxKRRKKxpDKXXD',
    'tJKDwllltpllxJRXP',
    'lpppplqKKtuFqwKXK',
    '.eenuLMRJFSUulDXt',
    '.nuLSLExuLUSFlyP.',
    '.FuFQFelpDNwAlxx.',
    '.FlettyVNIVgo.p..',
    '.LnlDxJYTVZjC....',
    'LSuelpqIXYZZZZ...',
    'SSF.elpwKVYZZY...',
    'SSL...vEMMMTVO...',
    'FLF..oLTTLFwA....',
    '.uv.cBRXVRLS.....',
    '....cGKXTMvLU....',
    '....ciNZZBgrF....',
    '.....bIVYBgHi....',
    '.....iyOYOir.....',
    '....ourvGFrFF....',
    '....onfivFoFL....',
    '....ccCC...BL....',
    '....dhoHOTVLSF...',
    '....CjiOZZVUSn...',
    '....bccvNNFYs....',
    '....bcdggggjc....',
    '....cddhdhkkc....',
    '....chmzzzzmd....',
    '....bdhmzzmhc....',
    '....aabccccba....',
    '.....lINNva......',
    '....flETNtlv.....',
    '....eqwwDDKVO....',
    '....eqxyyHKOOv...',
    '....ffiiiooooi...',
  ],
  right: [
    '.........vy......',
    '...vDN..iJP......',
    '...rtJPKtJPy.....',
    '...rqxJPDDKtHP...',
    '..qtKKxJKwqDRXA..',
    '.etKRPDtDylwDKy..',
    '.qJRPtKRXPwKDlq..',
    'qDPPDJPXXPqDPPXD.',
    'xJKKDqpxxtlqRRXP.',
    'ltttplpDynulJPXR.',
    '.leluFKRJLUFpJRD.',
    '.nuLTLKDEUWLltPt.',
    '.uuLXFlltKDKfqy..',
    '.FlltpGAIOgr.pl..',
    '.LllDwVOOY.s.i...',
    'FLneppAXYZYCY....',
    'LSu.eltJTYZZZ....',
    'LSu..fxEJTVYO....',
    'FLF..nLSQFtA.....',
    '.Fu.bBRVXQSn.....',
    '....cPPNPMLS.....',
    '....crVZVogI.....',
    '....bbOYVjsr.....',
    '.....fDVVBsv.....',
    '....olvGGAFL.....',
    '....uffrEvuF.....',
    '....bjC....F.....',
    '....djrMOOBCL....',
    '....CcrVZZUCu....',
    '....gcbGTOsj.....',
    '....bccgogdd.....',
    '....bddddhkh.....',
    '....chzzzzmd.....',
    '....bdkmmmkc.....',
    '....abbcccbb.....',
    '.....qINvf.......',
    '....etQMxpo......',
    '....etDxyKRVB....',
    '....etyDHKOOG....',
    '....efffiioii....',
  ],
  top: [
    '..........##.......',
    '..........###......',
    '.....###.#####.....',
    '.....#########.....',
    '.....############..',
    '....##############.',
    '#################..',
    '##################.',
    '..#################',
    '..#################',
    '..#################',
    '..################.',
    '..################.',
    '..################.',
    '......##########...',
    '......#########....',
    '.......###..###....',
  ],
};
